import { task, exec, file } from "./deps.ts";
import * as log from "https://deno.land/std/log/mod.ts";
import * as fs  from "https://deno.land/std/fs/mod.ts";

export const msg = file({
  path: './msg.txt'
});

export const helloWorld = task({
  name: 'helloWorld',
  description: "foo",
  action: async () => {
    console.log("hello world");
    await fs.writeFileStr(msg.path, "hello world");
  },
  /*file_deps: [
    file({
      path: "./dnit.ts"   // any files generated by this script should depend on it
    })
  ],*/
  targets: [
    msg
  ],
  uptodate: () => false
});
