name: Test and Lint

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        deno: ["v2.4.3"]
        os: [ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
          cache: true

      - name: Run Deno lint
        run: deno lint

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        deno: ["v2.4.3", "v2.3.10"]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
          cache: true

      - name: Run Tests
        run: deno test -A
